In [1]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [2]:
s=pd.Series([100,200,300] ,index=['A','B','C'])
print(s)

A    100
B    200
C    300
dtype: int64

In [5]:
data={'maths':90,'physics':85,'chemistry':96}
s=pd.Series(data)
print(s)
iS=pd.Series([10,20,30,40])
print(s[0])

maths        90
physics      85
chemistry    96
dtype: int64
90

C:\Users\Ibscai04.DGVC-MCA\AppData\Local\Temp\ipykernel_11824\4040459880.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [16]:
s=pd.Series([100,200,300],index=['A','B','C'])
print(s['B'])
print(s[['A','C']])
s=pd.Series([10,20,30,40])
print(s.size)

200
A    100
C    300
dtype: int64
4

In [19]:
print(s.shape)

(4,)

In [18]:
print(s.dtype)

int64

In [7]:
s=pd.Series([10,20,30,40])
print(s+10)

0    20
1    30
2    40
3    50
dtype: int64

In [8]:
print(s*2)

0    20
1    40
2    60
3    80
dtype: int64

In [9]:
print("sum=",s.sum())
print("mean=",s.mean())
print("maximum=",s.max())
print("minimum=",s.min())

sum= 100
mean= 25.0
maximum= 40
minimum= 10

In [7]:
data={'roll no':[101,102,103],'name':['arun','priya','rahul'],'marks':[85,90,78]}
df=pd.DataFrame(data)
print(df)

   roll no   name  marks
0      101   arun     85
1      102  priya     90
2      103  rahul     78

In [12]:
print(df.shape)
print(df.columns)
print(df['name'])

(3, 3)
Index(['roll no', 'name', 'marks'], dtype='object')
0     arun
1    priya
2    rahul
Name: name, dtype: object

In [13]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [8]:
print(df.dtypes)

roll no     int64
name       object
marks       int64
dtype: object

In [9]:

print(df[['name','marks']])

    name  marks
0   arun     85
1  priya     90
2  rahul     78

In [10]:
print(df.loc[0])

roll no     101
name       arun
marks        85
Name: 0, dtype: object

In [11]:
print(df.loc[[0,2]])

   roll no   name  marks
0      101   arun     85
2      103  rahul     78

In [12]:
print(df.iloc[1])

roll no      102
name       priya
marks         90
Name: 1, dtype: object

In [13]:
print(df.iloc[[0,2]])

   roll no   name  marks
0      101   arun     85
2      103  rahul     78

In [2]:
print(df.iloc[0:2,1:3])

    name  marks
0   arun     85
1  priya     90

In [3]:
df['grade']=['A','A+','B']
print(df)

   roll no   name  marks grade
0      101   arun     85     A
1      102  priya     90    A+
2      103  rahul     78     B

In [8]:
df['marks']=df['marks']+5
print(df)

   roll no   name  marks
0      101   arun    100
1      102  priya    105
2      103  rahul     93

In [9]:

df.drop('grade',axis=1,inplace=True)

KeyError: "['grade'] not found in axis"

In [3]:
print(df)

   roll no   name  marks
0      101   arun     85
1      102  priya     90
2      103  rahul     78

In [10]:
print(df['marks'].sum())

298

In [11]:
print(df['marks'].mean())

99.33333333333333

In [12]:
print(df['marks'].max())

105

In [16]:
print(df['marks'].min())

93

In [15]:
df.sort_values('marks')

   roll no   name  marks
2      103  rahul     93
0      101   arun    100
1      102  priya    105

In [17]:
df.sort_values('marks',ascending=False)

   roll no   name  marks
1      102  priya    105
0      101   arun    100
2      103  rahul     93

In [1]:
import pandas as pd
data={'roll no':[101,102,103],'name':['arun','priya','rahul'],'marks':[85,90,78]}
df=pd.DataFrame(data)
print(df)

   roll no   name  marks
0      101   arun     85
1      102  priya     90
2      103  rahul     78

In [3]:
df.sort_values('marks')

   roll no   name  marks
2      103  rahul     78
0      101   arun     85
1      102  priya     90

In [4]:
df.sort_values('marks',ascending=False)

   roll no   name  marks
1      102  priya     90
0      101   arun     85
2      103  rahul     78

In [5]:
print(df[df['marks']>80])

   roll no   name  marks
0      101   arun     85
1      102  priya     90

In [6]:
print(df[df['marks']<90])

   roll no   name  marks
0      101   arun     85
2      103  rahul     78

In [13]:
data={'roll no':[101,102,103,104,105,106,107,108,109,110],'name':['arun','priya','rahul','ajay','pavi','ramesh','janani','darshan','hashu','varsha'],'marks':[85,90,78,67,99,77,82,79,90,78]}
df=pd.DataFrame(data)
print(df)

   roll no     name  marks
0      101     arun     85
1      102    priya     90
2      103    rahul     78
3      104     ajay     67
4      105     pavi     99
5      106   ramesh     77
6      107   janani     82
7      108  darshan     79
8      109    hashu     90
9      110   varsha     78

In [14]:
df.head()

   roll no   name  marks
0      101   arun     85
1      102  priya     90
2      103  rahul     78
3      104   ajay     67
4      105   pavi     99

In [15]:
df.tail()

   roll no     name  marks
5      106   ramesh     77
6      107   janani     82
7      108  darshan     79
8      109    hashu     90
9      110   varsha     78

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   roll no  10 non-null     int64
 1   name     10 non-null     object
 2   marks    10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [17]:
df.describe()

         roll no      marks
count   10.00000  10.000000
mean   105.50000  82.500000
std      3.02765   8.910044
min    101.00000  67.000000
25%    103.25000  78.000000
50%    105.50000  80.500000
75%    107.75000  88.750000
max    110.00000  99.000000